version: 2.1

jobs:
  commit-workflow:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: "install deps"
          command: "npm install"
      - run:
          name: "run linter"
          command: "npm check-lint"
